version: '3'

services:
  kibana:
    # kibana major version should be the same as elasticsearch version
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    restart: unless-stopped
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:5601/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      - elasticsearch
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    restart: unless-stopped
    environment:
      discovery.type: single-node

    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  es_data:
